# Only build vme if it was missing
ifneq ($(CONFIG_VME_BUS),m)
ifneq ($(CONFIG_VME_BUS),y)
obj-m := vmebus.o
vmebus-objs := tsi148.o vme_bridge.o vme_cesif.o vme_dma.o vme_irq.o vme_misc.o vme_window.o
endif
endif

